name: Auto Push Markdown Logs

on:
  push:
    paths:
      - 'cloud-support-track/**/*.md'

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Git User
        run: |
          git config user.name "azure-auto-bot"
          git config user.email "azurebot@example.com"

      - name: Add and Commit Markdown Files
        run: |
          git add cloud-support-track/**/*.md
          git commit -m "docs: auto-publish markdown logs [bot]" || echo "No changes to commit"

      - name: Push Changes
        run: git push
